server:
  port: 8701

#服务名
TEST:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka/,http://eureka8501.com:8501/eureka/,http://eureka8502.com:8502/eureka/


