AXLE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 8602

spring:
  datasource:
    url: jdbc:mysql://47.101.141.93:3333/hbds2005-2?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

