AXLE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 8620

spring:
  datasource:
    url: jdbc:mysql://172.19.16.73:3333/hbds2005-2?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

# Mybatis 配置
mybatis:
  typeAliasesPackage: com.siit.hotbox.entity
  mapperLocations: classpath:mappers/*.xml

